### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by CsharpNoobDude** [pydota2/pydota2#21]
Hi Nostrademous,

I just wanted to ask some things: 

1. Have you ceased developing the full overwrite project? I loved playing with it, but it is not working properly anymore :(.  

**2. How can I play with these bots? I really, really wanna see these here play / watch them play. How can I do that? What file do I have to start? I can not open the ".py" files.... What do I need to do?**

3. Is this project here as good as the other one was? I remember the kiting Sniper, holy shit.

4. Can I help? I am not that good with lua, but I might get into it.

Hope to get some answers from you.
A fan

**Comment by Nostrademous** [comment]
1) Yeah, the Full Overwrite Project was a proof-of-concept for me to see how mature Valve's API was and, honestly, to help them iron-out some of the kinks and bugs taking the "over-write everything" mentality as I saw many of the other bot developers only over-write hero-specific behavior. I don't intend to spend any more cycles on it and ask Chris to remove it from the Workshop. It got farther than I expected but it's past it's life-span at this point.

2. These bots you can't play with right now. They don't do anything to make it worth-while at this point. It's all about collecting the appropriate data for now and building up appropriate world-state models and Reinforcement Learning mechanisms so that we have super-human bots in the future. It's a long way to get there being that Valve seems to currently not be supporting bug-fixes in the API.

3. This is an even more ambitious project, but like the other ones, I'm using it as a personal learning platform to teach myself machine learning. I knew "nothing" other than the buzz words 2 months ago and now feel comfortable talking about various algorithms and the general RL approach, but still have to really get my hands dirty in actual implementation, which is what I'm doing here. With the help of lenLRX we are also working on writing a Dota2 simulator (which means we are basically creating our own version of Dota2 which runs without any GUI) to allow faster parallelized and episodic execution in support of machine learning.

4. For the current project you (and anyone else) can help at many layers. There is LUA coding for the Dota2-resident Bot code; there is Python coding for the Reinforcement Learning back-end server portion; there is C++ coding for the Dota2 simulator we are writing.

**Comment by CsharpNoobDude** [comment]
hmmmmmmmm. thank you!
